# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            James Leslie
tagline:          Ph.D Candidate
description:      Ph.D Candidate
url:              https://jeslie0.github.io
baseurl:          /

author:
  name:           'James Leslie'
  url:            jeslie0.github.io

plugins: [jekyll-paginate]
paginate:         5
paginate_path: "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
